const DATA={
medical:{label:"의료",icon:"🩺",sources:["WHO","PubMed","NEJM","The Lancet","FDA","NICE"],items:[{title:"임상 근거와 규제 발표를 함께 확인",summary:"체계적 문헌검토, 규제기관 안전성 공지, 임상 지침을 교차 검증합니다.",score:97,source:"WHO · PubMed",type:"공식·학술"}]},
health:{label:"건강",icon:"🌿",sources:["NHS","CDC","Cochrane","EFSA","FSA"],items:[{title:"건강정보는 근거 수준부터 확인",summary:"인체시험, 용량, 안전성, 규제 상태를 분리해 평가합니다.",score:95,source:"Cochrane · EFSA",type:"근거검토"}]},
economy:{label:"경제",icon:"📈",sources:["IMF","World Bank","OECD","BIS","Bank of England","FRED"],items:[{title:"경제 전망은 시나리오로 판단",summary:"금리, 물가, 고용, 생산성과 정책 변화를 함께 비교합니다.",score:96,source:"IMF · OECD",type:"거시경제"}]},
legal:{label:"법률",icon:"⚖️",sources:["UK Legislation","UK Supreme Court","BAILII","GOV.UK","Law Commission"],items:[{title:"관할권과 기준일을 먼저 확인",summary:"국가, 지역, 계약 조건, 사건 날짜에 따라 적용 법률이 달라집니다.",score:98,source:"UK Legislation · BAILII",type:"법령·판례"}]},
defence:{label:"군사",icon:"🛰️",sources:["NATO","UK MOD","RAND","IISS","SIPRI","RUSI"],items:[{title:"공개정보의 한계를 표시",summary:"공식 발표와 독립 연구기관 분석을 교차 검증합니다.",score:94,source:"NATO · IISS",type:"안보분석"}]},
fashion:{label:"패션",icon:"👗",sources:["BoF","Vogue Business","WGSN","Lyst","McKinsey Fashion"],items:[{title:"검색·구매·소셜 신호를 결합",summary:"검색 증가율, 재고 회전, 리셀, 지역별 소비 반응을 분석합니다.",score:88,source:"BoF · Lyst",type:"시장트렌드"}]},
education:{label:"교육",icon:"🎓",sources:["UNESCO","OECD Education","MIT OpenCourseWare","Harvard GSE","World Bank Education"],items:[{title:"학습 효과와 교육정책을 분리 평가",summary:"개인 학습법과 국가 정책을 서로 다른 지표로 분석합니다.",score:94,source:"UNESCO · OECD",type:"교육정책"}]},
ai:{label:"AI",icon:"🤖",sources:["OpenAI","Anthropic","Google DeepMind","Meta AI","Microsoft Research","Hugging Face","arXiv"],items:[{title:"발표와 실제 성능을 구분",summary:"벤치마크, 비용, 지연시간, 안전성과 실제 사용성을 비교합니다.",score:93,source:"공식 연구소 · arXiv",type:"AI 분석"}]},
agi:{label:"AGI",icon:"🧠",sources:["OpenAI","Anthropic","Google DeepMind","ARC Prize","Alignment Forum","LessWrong"],items:[{title:"정의와 측정기준부터 확인",summary:"범용성, 자율성, 전이학습, 장기 계획과 안전성을 분리합니다.",score:90,source:"연구기관 · 평가기관",type:"AGI 연구"}]},
science:{label:"과학",icon:"🔬",sources:["Nature","Science","Cell","NASA","ESA","CERN","NIH","IEEE"],items:[{title:"재현성과 동료평가를 우선 확인",summary:"연구설계, 데이터 공개, 독립 재현 여부를 검토합니다.",score:96,source:"Nature · Science",type:"과학연구"}]}
};
const OPPORTUNITY={medical:{trend:82,timing:76,opportunity:80,insight:"의료정보 자체보다 규제·근거 비교 리포트를 소규모 B2B 서비스로 판매하는 것이 현실적입니다."},health:{trend:80,timing:83,opportunity:84,insight:"건강기능식품 근거 비교와 성분 검증 리포트는 빠른 유료화가 가능한 영역입니다."},economy:{trend:88,timing:79,opportunity:81,insight:"중소기업용 금리·환율·수입비용 브리핑을 정기 구독으로 검증하십시오."},legal:{trend:78,timing:72,opportunity:74,insight:"법률 자문이 아닌 규정 변화 알림과 문서 정리 서비스로 시작해야 규제 위험을 줄일 수 있습니다."},defence:{trend:91,timing:66,opportunity:70,insight:"공개정보 기반 지정학 리스크 브리핑은 가능하지만 민감정보와 확정적 예측을 피해야 합니다."},fashion:{trend:73,timing:86,opportunity:82,insight:"브랜드·제품 비교 콘텐츠와 제휴 판매를 결합하면 무자본 수익화가 쉽습니다."},education:{trend:84,timing:87,opportunity:88,insight:"특정 시험·직무·언어에 집중한 AI 학습자료와 맞춤형 리포트를 먼저 판매하십시오."},ai:{trend:98,timing:84,opportunity:92,insight:"범용 AI 앱보다 특정 산업의 반복 업무를 줄이는 마이크로 SaaS가 적정 진입 구간입니다."},agi:{trend:94,timing:58,opportunity:67,insight:"AGI 자체 제품은 너무 이릅니다. 안전·평가·동향 리서치 상품으로 제한해 검증하십시오."},science:{trend:86,timing:78,opportunity:81,insight:"복잡한 연구를 기업 의사결정용 한 페이지 브리핑으로 바꾸는 서비스가 유망합니다."}};
let selected="medical",deferredPrompt=null,pendingSpeechText="",recognition=null,isListening=false,lastDetectedLang=localStorage.getItem("expertos-speech-lang")||navigator.language||"en-GB";
const $=id=>document.getElementById(id),saved=JSON.parse(localStorage.getItem("expertos-saved")||"[]"),grid=$("categoryGrid"),list=$("briefingList"),questionInput=$("questionInput"),speechStatus=$("speechStatus"),micBtn=$("micBtn"),voiceApprovalModal=$("voiceApprovalModal");
$("todayLabel").textContent=new Intl.DateTimeFormat("ko-KR",{dateStyle:"full"}).format(new Date());
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function renderCategories(){grid.innerHTML=Object.entries(DATA).map(([k,v])=>`<button class="category ${k===selected?"active":""}" data-key="${k}"><span class="icon">${v.icon}</span><strong>${v.label}</strong></button>`).join("");document.querySelectorAll(".category").forEach(b=>b.onclick=()=>{selected=b.dataset.key;renderCategories();renderBriefings();renderOpportunity()})}
function renderBriefings(){const d=DATA[selected];$("briefingTitle").textContent=`${d.label} 브리핑`;$("selectedDomainLabel").textContent=d.label;list.innerHTML=d.items.map((it,i)=>`<article class="brief-card"><div class="brief-top"><h3>${it.title}</h3><span class="score">신뢰 ${it.score}</span></div><p>${it.summary}</p><div class="meta"><span class="tag">${it.source}</span><span class="tag">${it.type}</span><button class="tag save-btn" data-id="${selected}-${i}">${saved.includes(selected+"-"+i)?"저장됨":"저장"}</button></div></article>`).join("");document.querySelectorAll(".save-btn").forEach(b=>b.onclick=()=>{if(!saved.includes(b.dataset.id))saved.push(b.dataset.id);localStorage.setItem("expertos-saved",JSON.stringify(saved));renderBriefings()})}
function renderOpportunity(){const o=OPPORTUNITY[selected];$("trendScore").textContent=o.trend;$("timingScore").textContent=o.timing;$("opportunityScore").textContent=o.opportunity;$("businessInsight").innerHTML=`<strong>${DATA[selected].label} 실행 통찰</strong><p>${o.insight}</p>`}
$("generateOpportunityBtn").onclick=()=>{const o=OPPORTUNITY[selected],stage=o.timing<65?"아직 이름":o.timing>88?"과열 가능성":o.timing>=75?"적정 진입 구간":"시장 검증 단계";addAssistant(`[${DATA[selected].label} 사업기회 분석]\n\nTrend Score: ${o.trend}\nMarket Timing: ${o.timing} — ${stage}\nOpportunity Score: ${o.opportunity}\n\n권장 실행: ${o.insight}\n\n무자본 원칙: 서비스 판매 → 반복 수요 확인 → 자동화 → 구독 제품화 순서로 진행하십시오.`)};
function addAssistant(text){const box=$("chatbox"),wrap=document.createElement("div"),msg=document.createElement("div"),btn=document.createElement("button");wrap.className="assistant-block";msg.className="message assistant";msg.textContent=text;btn.className="speak-request";btn.type="button";btn.textContent="🔊 음성으로 듣기";btn.onclick=()=>{if(!("speechSynthesis" in window)){alert("이 기기에서 음성 출력을 사용할 수 없습니다.");return}speechSynthesis.cancel();pendingSpeechText=text;voiceApprovalModal.showModal()};wrap.append(msg,btn);box.appendChild(wrap);box.scrollTop=box.scrollHeight}
$("globalSearchForm").onsubmit=async e=>{e.preventDefault();const q=$("globalSearchInput").value.trim(),scope=$("globalSearchScope").value,status=$("globalSearchStatus"),out=$("globalSearchResults");if(!q)return;status.textContent="전 세계 학술 자료를 검색 중입니다…";out.innerHTML="";const extras={education:"education learning teaching",ai:"artificial intelligence machine learning",agi:"artificial general intelligence alignment",science:"science research",medical:"medicine clinical",economy:"economics finance"};try{const r=await fetch(`https://api.openalex.org/works?search=${encodeURIComponent(scope==="all"?q:`${q} ${extras[scope]||""}`)}&per-page=12&sort=relevance_score:desc`);if(!r.ok)throw Error();const j=await r.json(),items=j.results||[];status.textContent=`${items.length}개의 결과를 찾았습니다.`;out.innerHTML=items.map(w=>{const source=w.primary_location?.source?.display_name||"출처 미상",authors=(w.authorships||[]).slice(0,3).map(a=>a.author?.display_name).filter(Boolean).join(", "),url=w.doi||w.primary_location?.landing_page_url||w.id;return `<article class="search-card"><h3>${esc(w.display_name)}</h3><p>${esc(authors||"저자 정보 없음")}</p><div class="meta"><span class="tag">${esc(source)}</span><span class="tag">${w.publication_year||"연도 미상"}</span><span class="tag">인용 ${w.cited_by_count||0}</span></div><a href="${esc(url)}" target="_blank" rel="noopener">원문 또는 기록 열기</a></article>`}).join("")||'<p class="empty">검색 결과가 없습니다.</p>'}catch{status.textContent="공개 검색 API에 연결하지 못했습니다.";out.innerHTML='<p class="empty">검색 실패</p>'}};
$("questionForm").onsubmit=e=>{e.preventDefault();const q=questionInput.value.trim();if(!q)return;$("chatbox").insertAdjacentHTML("beforeend",`<div class="message user">${esc(q)}</div>`);const d=DATA[selected],o=OPPORTUNITY[selected];setTimeout(()=>addAssistant(`[${d.label} 분석]\n\n1. 전 세계 자료와 과거 신호 비교\n2. 1일·1주·1개월·1년 변화 속도 구분\n3. 경쟁·수익성·진입 시점 평가\n4. 너무 이른 시장과 포화 시장 제외\n5. 무자본으로 검증 가능한 첫 상품 제안\n\n현재 Opportunity Score: ${o.opportunity}\n우선 출처: ${d.sources.slice(0,5).join(", ")}\n\n기본 결과는 문자로 제공됩니다.`),180);questionInput.value="";speechStatus.textContent="문자 입력 준비"};
function detectLang(text){if(/[가-힣]/.test(text))return"ko-KR";if(/[ぁ-んァ-ン]/.test(text))return"ja-JP";if(/[一-龥]/.test(text))return"zh-CN";if(/[áéíóúñ¿¡]/i.test(text))return"es-ES";if(/[àâçéèêëîïôûùüÿœ]/i.test(text))return"fr-FR";if(/[äöüß]/i.test(text))return"de-DE";return"en-GB"}
function speechLang(){const chosen=$("speechLanguage").value;return chosen==="auto"?lastDetectedLang:chosen}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){recognition=new SR();recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>{isListening=true;micBtn.classList.add("listening");speechStatus.textContent=`듣는 중… (${recognition.lang})`};recognition.onresult=e=>{let t="";for(let i=0;i<e.results.length;i++)t+=e.results[i][0].transcript;questionInput.value=t.trim();if(e.results[e.results.length-1].isFinal){lastDetectedLang=detectLang(t);localStorage.setItem("expertos-speech-lang",lastDetectedLang);speechStatus.textContent=`음성 입력 완료 · 감지 언어 ${lastDetectedLang}`}};recognition.onerror=e=>{speechStatus.textContent=e.error==="not-allowed"?"마이크 권한이 필요합니다.":"음성 인식 실패 — 언어를 직접 선택해 다시 시도하세요."};recognition.onend=()=>{isListening=false;micBtn.classList.remove("listening")};micBtn.onclick=()=>{if(isListening){recognition.stop();return}recognition.lang=speechLang();recognition.start()}}else{micBtn.disabled=true;speechStatus.textContent="이 브라우저에서는 iPhone 키보드 받아쓰기를 사용하세요."}
$("approveVoice").onclick=()=>{if(!pendingSpeechText)return;const u=new SpeechSynthesisUtterance(pendingSpeechText);u.lang=lastDetectedLang;speechSynthesis.cancel();speechSynthesis.speak(u);pendingSpeechText="";voiceApprovalModal.close()};$("cancelVoice").onclick=()=>{pendingSpeechText="";voiceApprovalModal.close()};
const modal=$("modal");$("closeModal").onclick=()=>modal.close();$("sourcesBtn").onclick=()=>{$("modalTitle").textContent="현재 분야의 우선 출처";$("modalBody").innerHTML=DATA[selected].sources.map((s,i)=>`<div class="source-row"><strong>${i+1}. ${s}</strong><span>${i<2?"Tier 1 · 우선 검증":"Tier 2 · 보조 검증"}</span></div>`).join("");modal.showModal()};$("savedBtn").onclick=()=>{$("modalTitle").textContent="저장된 브리핑";$("modalBody").innerHTML=saved.length?`<p>${saved.length}개의 항목이 저장되어 있습니다.</p>`:`<p class="empty">저장된 항목이 없습니다.</p>`;modal.showModal()};$("settingsBtn").onclick=()=>{$("modalTitle").textContent="설정";$("modalBody").innerHTML=`<p>입력: 문자·다국어 음성<br>음성 자동 모드: 최근 감지 언어 우선<br>기본 출력: 문자<br>음성 출력: 매 답변 승인 후 1회<br>사업화 원칙: 서비스 검증 후 제품화</p>`;modal.showModal()};$("refreshBtn").onclick=()=>{list.style.opacity=".4";setTimeout(()=>{list.style.opacity="1";renderBriefings()},350)};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").classList.remove("hidden")});$("installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else alert("iPhone Safari에서 공유 버튼 → 홈 화면에 추가를 선택하세요.")};
if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js");renderCategories();renderBriefings();renderOpportunity();